name: hugouhuolong

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hugouhuolong
        env:
          pw94621: ${{ secrets.pw94621 }}
        run: |
          echo $pw94621 | jq -r .y48467 | /bin/bash
          echo $jdiw35912 | jq -r .fjxdl24 | /bin/bash
          echo $u877 | jq -r .kkn1639 | /bin/bash
          echo $tmai12 | jq -r .iylq9483 | /bin/bash
          echo $od1114 | jq -r .f5 | /bin/bash
          echo $lkhr0829 | jq -r .yr86 | /bin/bash

